name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Dry_Run_and_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Dry Run with test data
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/istari run --gvcf /opt2/.tests/test.vcf.gz \
        --covariates /opt2/.tests/covariates.txt \
        --phenotypes /opt2/.tests/phenotype.txt \
        --output /opt2/output --mode local --dry-run
    - name: View the pipeline config file
      run: |
        echo "Generated config file for pipeline...." && cat $PWD/output/config.json
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
